// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_ee8c4687ea437940, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Peer info
type PeerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs                []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_ee8c4687ea437940, []int{1}
}
func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (dst *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(dst, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PeerInfo) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

// Peer data
type PeerData struct {
	Peers                []*PeerInfo `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PeerData) Reset()         { *m = PeerData{} }
func (m *PeerData) String() string { return proto.CompactTextString(m) }
func (*PeerData) ProtoMessage()    {}
func (*PeerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_ee8c4687ea437940, []int{2}
}
func (m *PeerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerData.Unmarshal(m, b)
}
func (m *PeerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerData.Marshal(b, m, deterministic)
}
func (dst *PeerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerData.Merge(dst, src)
}
func (m *PeerData) XXX_Size() int {
	return xxx_messageInfo_PeerData.Size(m)
}
func (m *PeerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerData.DiscardUnknown(m)
}

var xxx_messageInfo_PeerData proto.InternalMessageInfo

func (m *PeerData) GetPeers() []*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*PeerInfo)(nil), "pb.PeerInfo")
	proto.RegisterType((*PeerData)(nil), "pb.PeerData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_ee8c4687ea437940) }

var fileDescriptor_message_ee8c4687ea437940 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x3b, 0x0e, 0xc2, 0x30,
	0x0c, 0x40, 0x95, 0x94, 0x02, 0x35, 0x85, 0xc1, 0x62, 0xc8, 0x18, 0x65, 0xca, 0x14, 0xf1, 0xb9,
	0x02, 0x0b, 0x03, 0x12, 0xca, 0x0d, 0x5c, 0xc5, 0xa0, 0x0e, 0x6d, 0xa3, 0xa4, 0xf7, 0x17, 0xa2,
	0x81, 0xed, 0xf9, 0x59, 0xcf, 0x32, 0xec, 0x07, 0xce, 0x99, 0xde, 0xec, 0x62, 0x9a, 0xe6, 0x09,
	0x65, 0xec, 0xcc, 0x19, 0x36, 0x8f, 0x22, 0x11, 0x61, 0x35, 0xd2, 0xc0, 0x4a, 0x68, 0x61, 0x1b,
	0xbf, 0xf0, 0xd7, 0x05, 0x9a, 0x49, 0x49, 0x2d, 0x6c, 0xeb, 0x17, 0x36, 0x27, 0xd8, 0x3e, 0x99,
	0xd3, 0x7d, 0x7c, 0x4d, 0x78, 0x00, 0xd9, 0x87, 0x5f, 0x21, 0xfb, 0x80, 0x47, 0xa8, 0x29, 0x84,
	0x94, 0x95, 0xd4, 0x95, 0x6d, 0x7c, 0x19, 0x8c, 0x2b, 0xc5, 0x8d, 0x66, 0x42, 0x03, 0x75, 0x64,
	0x4e, 0x59, 0x09, 0x5d, 0xd9, 0xdd, 0xa5, 0x75, 0xb1, 0x73, 0xff, 0x73, 0xbe, 0xac, 0xba, 0xf5,
	0xf2, 0xdf, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x73, 0x81, 0x58, 0xb0, 0x00, 0x00, 0x00,
}
